services:
  backend:
    build:
      contex: backend
      target: builder
    secrets:
      - db - password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db - password
    volumes:
      -db-data:/var/lib/postgresql/data
    environment:
      - POSTGES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healtcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./prixy/nginx.conf
        target: /etx/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend

